Fixes CodeClimate issues for SemVerVersionInfo
corgibytes/freshli pull request #222
Opened 2021-01-23 18:46 UTC by dfar-io

Refactored this file to remove all CodeClimate issues since it was the file with the lowest grade available. Of note - I've changed it over to be more functional, initializing the values on construction and removing a lot of the unused modification methods.

2021-02-03 16:02 UTC, dan-hein requested changes
These are some really good changes! There are a few minor adjustments that we discussed that would be good to change for readability, but otherwise, this is a great step forward! The main thing I'd focus on next is making sure that we have proper test coverage for the newly broken out methods.

2021-02-05 14:51 UTC, dfar-io commented on Freshli/Languages/Python/PythonVersionInfo.cs
> +      if (datePublished.HasValue) { DatePublished = datePublished.Value; }
Looks like without changing `IVersionInfo`, I need to not assign to `DatePublished` unless there is a value provided... leaving this as is.

2021-02-05 15:37 UTC, dfar-io commented on Freshli/LibYearCalculator.cs
> +    // We should look into moving this into LibYearPackageResult.cs
On second thought, this is going to take more work than I would like to tackle, going to leave as is.

2021-02-05 15:39 UTC, dfar-io commented on Freshli/Languages/Python/PythonVersionInfo.cs
>      ) {
I remember now - ends up changing a number of files that are using the cast for comparison - I think we should revisit this if it becomes a problem.

2021-02-11 22:09 UTC, dan-hein approved these changes

2021-02-12 14:39 UTC, merged